### PR TITLE
Serviceaccount

### LINKED ISSUE #8: Created user cannot authenticate
I've created users with operation/all-namespaces/read-write permissions.
When I merge into my existing /config:
k get pods
`error: You must be logged in to the server (Unauthorized)`

k version
`error: You must be logged in to the server (the server has asked for the client to provide credentials)`

When I point to generated kube config saved to a file, and  k version:
`Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`

### LINKED ISSUE #18: How do with EKS ?
I tried with AKS, it works well. When I try with EKS, this approach failed due to IAM based authentication. Any workaround?

### PR DESCRIPTION
**Pull request by iknite**
Hi **$TEAM**!

Finally is here the refactor to be able to use permission-manager in EKS. It will use the new deployment method and an new tag 1.6.0, so please review the docs/installation.md to test it. 

- Added tag v1.6.0
- Closes #8
- Closes #18

### CODE REVIEW

File: internal/kubeconfig/certificate.go [hunk 1]
```diff
@@ -148,9 +148,13 @@ func createCSR(username string, privateKey *rsa.PrivateKey) []byte {
...
 	if err != nil {
-		log.Printf("Unable to get kubeconfig.\n%v", err)
-		os.Exit(1)
+		log.Fatalf("Unable to get kubeconfig.\n%v", err)
 	}
 
-	return base64.StdEncoding.EncodeToString(config.CAData)
+	CAData, err := ioutil.ReadFile(config.CAFile)
+	if err != nil {
+		log.Fatalf("Unable to read kubeconfig file.\n%v", err)
```
Comment (angelbarrera92) [inline internal/kubeconfig/certificate.go:156]: We have to test running it outside a kind cluster (locally with go run...) and a kubeconfig file instead of a serviceaccount. 

commented just to keep it in mind
